FROM redis:6.2.0

ENV ALLOW_EMPTY_PASSWORD='yes'
ENV REDIS_TLS_ENABLED='yes'
ENV REDIS_TLS_PORT='6380'
ENV REDIS_TLS_CERT_FILE='/usr/local/etc/redis/redis.crt'
ENV REDIS_TLS_KEY_FILE='/usr/local/etc/redis/redis.key'
ENV REDIS_TLS_CA_FILE='/usr/local/etc/redis/ca.crt'

USER root
