version: '3'

volumes:
  redis:
    driver: local

networks:
  redis:
    internal: true
    driver: bridge

services:
  redis-simple:
    image: redis:6.2.0
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: "redisTLS2022@@"
      REDIS_TLS_ENABLED: "no"
    command: ["sh", "-c", "/usr/local/share/scripts/entrypoint-redis-server.sh"]
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "../../scripts:/usr/local/share/scripts"
      - "../../_data:/data"
    ports:
      - "6379:6379"

  redis-ui:
    # https://github.com/patrikx3/redis-ui
    image: patrikx3/p3x-redis-ui:latest
    restart: always
    environment:
      P3XRS_PORT: "8000"
      REDIS_URL: "redis-simple"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redisTLS2022@@"
      REDIS_TLS_ENABLED: "no"
    command: ["sh", "-c", "/bin/bash /usr/local/share/scripts/entrypoint-redis-server-healthcheck.sh && sh -c /usr/local/share/scripts/entrypoint-redis-ui.sh"]
    volumes:
      - "../../scripts:/usr/local/share/scripts"
      - "../../_settings:/settings"
    ports:
      - 90:8000
    links:
      - redis-simple
    depends_on:
      redis-simple:
        condition: service_started