version: '3.9'

volumes:
  redis:
    driver: local

services:
  redis:
    image: redis-local:6.2.0
    restart: always
    build:
      context: .
      dockerfile: ./src/docker/redis/Dockerfile
    command: ["/script/entrypoint.sh"]
    volumes:
      - "./src/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - 6380:6380
    
  redis-health:
    image: redis-local:6.2.0
    command: redis-cli -h redis -p 6380 -n 0 -e --stat -a redisTLSTest2021@@ --cert /usr/local/etc/redis/redis.crt --key /usr/local/etc/redis/redis.key --cacert /usr/local/etc/redis/ca.crt --tls
    depends_on:
      - redis
